port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
geodata-mode: true
geox-url:
  geoip: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
  mmdb: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
proxies:
- name: è¶Šå—_12
  server: 103.186.154.18
  port: 38388
  type: ss
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  region: å…¶ä»–åœ°åŒº
- name: è·å…°_8
  network: ws
  port: 8880
  server: 188.164.248.63
  servername: sg.laoyoutiao.link
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³
  region: å¾·å›½
- name: ç‘å£«_1
  type: ss
  server: 204.136.10.115
  port: 1866
  password: oXGp1+ihlfKg826H
  cipher: chacha20-ietf-poly1305
  region: ç¾å›½
- name: è‹±å›½_60
  type: vmess
  server: 51.38.64.209
  port: 44023
  uuid: 7da457da-ed0f-437d-c81d-6c35885bbea3
  alterId: 0
  cipher: auto
  network: tcp
- name: ä¼¯åˆ©å…¹_5
  server: 45.135.235.194
  port: 2096
  type: trojan
  password: ttfang
  sni: ttfang.fange.me
  skip-cert-verify: false
  network: ws
  ws-opts:
    path: TelegramğŸ‡¨ğŸ‡³
    headers:
      Host: ttfang.fange.me
- name: å°æ¹¾_75
  server: 125.228.31.10
  port: 10113
  type: ss
  cipher: chacha20-ietf-poly1305
  password: b73652cc-087a-4d4b-87c3-c4b20d514df1
  udp: true
- name: å°æ¹¾_135
  server: 36.232.80.194
  port: 10114
  type: ss
  cipher: chacha20-ietf-poly1305
  password: d008fb00-a78b-4b0e-b538-f779791978af
  udp: true
- name: å°æ¹¾_152
  server: 125.229.191.104
  port: 10033
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 5950073b-6786-4325-bad8-c1d26600172a
  udp: true
- name: å°æ¹¾_235
  server: 1.165.72.230
  port: 10035
  type: ss
  cipher: chacha20-ietf-poly1305
  password: ab3696b7-e2ab-4b92-b904-cb9386d42d30
  udp: true
- name: å°æ¹¾_248
  server: 1.170.53.208
  port: 10152
  type: ss
  cipher: chacha20-ietf-poly1305
  password: f50fbfcf-4606-489b-a341-7853239863b1
  udp: true
- name: å°æ¹¾_508
  server: 125.230.12.33
  port: 10004
  type: ss
  cipher: chacha20-ietf-poly1305
  password: b73652cc-087a-4d4b-87c3-c4b20d514df1
  udp: true
- name: å°æ¹¾_547
  server: 114.46.79.253
  port: 10068
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 12593427-fa92-4566-bc4a-0c5b4a10d8a7
  udp: true
- name: å°æ¹¾_638
  server: 1.165.88.120
  port: 10069
  type: ss
  cipher: chacha20-ietf-poly1305
  password: f5f728b9-7846-47e6-a537-dca12abae9fb
  udp: true
- name: å°æ¹¾_742
  server: 36.232.100.121
  port: 10146
  type: ss
  cipher: chacha20-ietf-poly1305
  password: ffe839b1-756c-40ff-bfc6-8dfb5678afc1
  udp: true
- name: å°æ¹¾_768
  server: 114.46.79.253
  port: 10068
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 33f49e36-7dc4-4948-822a-15f619016e00
  udp: true
- name: å°æ¹¾_839
  server: 36.234.120.74
  port: 10075
  type: ss
  cipher: chacha20-ietf-poly1305
  password: b8aef377-0079-4cd9-bb26-3eb848d67671
  udp: true
- name: å°æ¹¾_849
  server: 1.165.100.2
  port: 10032
  type: ss
  cipher: chacha20-ietf-poly1305
  password: c616952f-33eb-4521-ba72-d5546290cc33
  udp: true
- name: å°æ¹¾_1050
  server: 111.253.192.138
  port: 10151
  type: ss
  cipher: chacha20-ietf-poly1305
  password: b8aef377-0079-4cd9-bb26-3eb848d67671
  udp: true
- name: å°æ¹¾_1058
  server: 59.126.32.59
  port: 10066
  type: ss
  cipher: chacha20-ietf-poly1305
  password: d8c7e2fc-ba02-4665-8a92-530a0563ae66
  udp: true
- name: å°æ¹¾_1216
  server: 36.232.80.11
  port: 10134
  type: ss
  cipher: chacha20-ietf-poly1305
  password: ab3696b7-e2ab-4b92-b904-cb9386d42d30
  udp: true
- name: å°æ¹¾_1291
  server: 36.234.95.185
  port: 10078
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 33f49e36-7dc4-4948-822a-15f619016e00
  udp: true
- name: å°æ¹¾_1660
  server: 125.229.191.101
  port: 10007
  type: ss
  cipher: chacha20-ietf-poly1305
  password: ab3696b7-e2ab-4b92-b904-cb9386d42d30
  udp: true
- name: å°æ¹¾_1772
  server: 118.170.246.125
  port: 10006
  type: ss
  cipher: chacha20-ietf-poly1305
  password: ab3696b7-e2ab-4b92-b904-cb9386d42d30
  udp: true
- name: å°æ¹¾_1851
  server: 114.46.112.253
  port: 10053
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 33f49e36-7dc4-4948-822a-15f619016e00
  udp: true
- name: å°æ¹¾_2011
  server: 36.232.88.152
  port: 10123
  type: ss
  cipher: chacha20-ietf-poly1305
  password: d008fb00-a78b-4b0e-b538-f779791978af
  udp: true
- name: å°æ¹¾_2083
  server: 1.170.41.78
  port: 10101
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 23ee8717-f4b7-40ed-ad7a-b418e2715ff8
  udp: true
- name: å°æ¹¾_2154
  server: 36.234.106.51
  port: 10051
  type: ss
  cipher: chacha20-ietf-poly1305
  password: c616952f-33eb-4521-ba72-d5546290cc33
  udp: true
- name: å°æ¹¾_2173
  server: 1.165.69.73
  port: 10029
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 3babe1aa-953b-4b53-801d-be9e5c548d7a
  udp: true
- name: å°æ¹¾_2195
  server: 1.170.5.127
  port: 10083
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 3babe1aa-953b-4b53-801d-be9e5c548d7a
  udp: true
- name: å°æ¹¾_2270
  server: 36.234.116.8
  port: 10042
  type: ss
  cipher: chacha20-ietf-poly1305
  password: b73652cc-087a-4d4b-87c3-c4b20d514df1
  udp: true
- name: å°æ¹¾_2328
  server: 1.170.18.49
  port: 10117
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 3babe1aa-953b-4b53-801d-be9e5c548d7a
  udp: true
- name: å°æ¹¾_2585
  server: 36.234.95.185
  port: 10078
  type: ss
  cipher: chacha20-ietf-poly1305
  password: b73652cc-087a-4d4b-87c3-c4b20d514df1
  udp: true
- name: å°æ¹¾_2769
  server: 114.33.53.80
  port: 10047
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 0d80c4af-f334-4491-9dac-a393b52e430e
  udp: true
- name: å°æ¹¾_2880
  server: 114.46.91.182
  port: 10071
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 12593427-fa92-4566-bc4a-0c5b4a10d8a7
  udp: true
- name: å°æ¹¾_2953
  server: 114.33.53.213
  port: 10037
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 5950073b-6786-4325-bad8-c1d26600172a
  udp: true
- name: None_1695
  type: vless
  server: 104.24.248.141
  port: 80
  uuid: dfdf1c0a-5e52-4746-88bd-19d4e4ac7853
  network: ws
  tls: false
  flow: null
  ws-opts:
    path: '%2F---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1---proNG1%3Fed%3D2560'
    headers:
      Host: barayeiranmahsang.juveitaly.dpdns.org
proxy-groups:
- name: èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - è‡ªåŠ¨é€‰æ‹©
  - æ•…éšœè½¬ç§»
  - DIRECT
  - æ‰‹åŠ¨é€‰æ‹©
- name: è‡ªåŠ¨é€‰æ‹©
  type: url-test
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies:
  - è·å…°_8
  - ä¼¯åˆ©å…¹_5
  - None_1695
  - å°æ¹¾_2769
  - å°æ¹¾_849
  - å°æ¹¾_1851
  - å°æ¹¾_2585
  - å°æ¹¾_508
  - å°æ¹¾_547
  - å°æ¹¾_1058
  - å°æ¹¾_742
  - å°æ¹¾_2083
  - å°æ¹¾_2173
  - å°æ¹¾_2880
  - å°æ¹¾_638
  - è‹±å›½_60
  - å°æ¹¾_1050
  - å°æ¹¾_2953
  - å°æ¹¾_2270
  - å°æ¹¾_2328
  - å°æ¹¾_1291
  - å°æ¹¾_2154
  - å°æ¹¾_2195
  - å°æ¹¾_1216
  - å°æ¹¾_135
  - å°æ¹¾_1772
  - å°æ¹¾_2011
  - å°æ¹¾_768
  - å°æ¹¾_235
  - å°æ¹¾_75
  - ç‘å£«_1
  - å°æ¹¾_839
  - å°æ¹¾_1660
  - å°æ¹¾_152
  - è¶Šå—_12
  - å°æ¹¾_248
  url: http://www.pinterest.com
  interval: 300
  tolerance: 50
- name: æ•…éšœè½¬ç§»
  type: fallback
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies:
  - è·å…°_8
  - ä¼¯åˆ©å…¹_5
  - None_1695
  - å°æ¹¾_2769
  - å°æ¹¾_849
  - å°æ¹¾_1851
  - å°æ¹¾_2585
  - å°æ¹¾_508
  - å°æ¹¾_547
  - å°æ¹¾_1058
  - å°æ¹¾_742
  - å°æ¹¾_2083
  - å°æ¹¾_2173
  - å°æ¹¾_2880
  - å°æ¹¾_638
  - è‹±å›½_60
  - å°æ¹¾_1050
  - å°æ¹¾_2953
  - å°æ¹¾_2270
  - å°æ¹¾_2328
  - å°æ¹¾_1291
  - å°æ¹¾_2154
  - å°æ¹¾_2195
  - å°æ¹¾_1216
  - å°æ¹¾_135
  - å°æ¹¾_1772
  - å°æ¹¾_2011
  - å°æ¹¾_768
  - å°æ¹¾_235
  - å°æ¹¾_75
  - ç‘å£«_1
  - å°æ¹¾_839
  - å°æ¹¾_1660
  - å°æ¹¾_152
  - è¶Šå—_12
  - å°æ¹¾_248
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: æ‰‹åŠ¨é€‰æ‹©
  type: select
  proxies:
  - è·å…°_8
  - ä¼¯åˆ©å…¹_5
  - None_1695
  - å°æ¹¾_2769
  - å°æ¹¾_849
  - å°æ¹¾_1851
  - å°æ¹¾_2585
  - å°æ¹¾_508
  - å°æ¹¾_547
  - å°æ¹¾_1058
  - å°æ¹¾_742
  - å°æ¹¾_2083
  - å°æ¹¾_2173
  - å°æ¹¾_2880
  - å°æ¹¾_638
  - è‹±å›½_60
  - å°æ¹¾_1050
  - å°æ¹¾_2953
  - å°æ¹¾_2270
  - å°æ¹¾_2328
  - å°æ¹¾_1291
  - å°æ¹¾_2154
  - å°æ¹¾_2195
  - å°æ¹¾_1216
  - å°æ¹¾_135
  - å°æ¹¾_1772
  - å°æ¹¾_2011
  - å°æ¹¾_768
  - å°æ¹¾_235
  - å°æ¹¾_75
  - ç‘å£«_1
  - å°æ¹¾_839
  - å°æ¹¾_1660
  - å°æ¹¾_152
  - è¶Šå—_12
  - å°æ¹¾_248
rules:
- DOMAIN,app.adjust.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,èŠ‚ç‚¹é€‰æ‹©
